@startuml

' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "ワークスペース" {
    *ID
    --
    *ワークスペース名
}

entity "チャネル" {
    *ID
    --
    *ワークスペースID
    *チャネル名
}

entity "メッセージ" {
    *ID
    --
    *ユーザーID
    *チャネルID
    *本文
    *親メッセージフラグ
}

entity "スレッド" {
    --
    *親メッセージID
    *子メッセージID
}


entity "ユーザー" {
    *ID
    --
    *表示名
}

ワークスペース ||.r.o{ チャネル
チャネル ||.r.o{ メッセージ
メッセージ ||.r.o{ スレッド
ユーザー }|.d.o{ ワークスペース
ユーザー }|.d.o{ チャネル
ユーザー ||.d.o{ メッセージ

note bottom of スレッド : スレッドの一番初めのメッセージを親メッセージIDとする

@enduml