@startuml

entity "ユーザー" {
    *ID
    --
    *表示名
}

entity "オブジェクト" {
    *ID
    --
    *ディレクトリID
    *ファイルID
    *ルートフラグ
    *作成者ID
}

entity "ディレクトリ" {
    *ID
    --
    *ディレクトリ名
}

entity "ドキュメント" {
    *ID
    --
    *ドキュメント名
}

entity "ドキュメント履歴" {
    *ID
    --
    *ドキュメントID
    *テキスト情報
    *最新フラグ
    *更新者ID
    *更新日時
}

entity "オブジェクト経路" {
    *ID
    --
    *先祖ID
    *子孫ID
    *深さ
}

ユーザー ||-r-|{ オブジェクト
オブジェクト ||-d-o| ドキュメント
オブジェクト ||-d-o| ディレクトリ
オブジェクト }|-r-|{ オブジェクト経路
オブジェクト }|-r-|{ オブジェクト経路
ドキュメント ||-d-|{ ドキュメント履歴

@enduml