@startuml

entity "リマインド" {
    *ID
    --
    *作成者ユーザー
    *宛先チャネル
    *メッセージ
    *チャネル
    *頻度ID
    *リマインド実行日時
    *リマインダー作成日時
}

entity "頻度" {
    *ID
    --
    *頻度種別
    *固有値
}


リマインド ||-r-|| 頻度

@enduml