@startuml

entity "ユーザー" {
    *ID
    --
    *表示名
}

entity "ワークスペース" {
    *ID
    --
    *ワークスペース名
}

entity "チャネル" {
    *ID
    --
    *ワークスペースID
    *チャネル名
}

entity "ワークスペース_ユーザー" {
    *ID
    --
    *ワーススペースID
    *ユーザーID
}

entity "チャネル_ユーザー" {
    *ID
    --
    *チャネルID
    *ユーザーID
}

entity "メッセージ" {
    *ID
    --
    *ユーザーID
    *チャネルID
    *本文
    *スレッドID
}

ユーザー ||-d-|{ ワークスペース_ユーザー
ワークスペース_ユーザー ||-d-|{ ワークスペース
ユーザー ||-d-|{ チャネル_ユーザー
チャネル_ユーザー }|-d-|| チャネル
ユーザー ||-d-o{ メッセージ
ワークスペース ||-r-o{ チャネル
チャネル ||-r-o{ メッセージ

@enduml